# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
matrix:
  include:
  - os: linux
    julia: 0.4
    sudo: required
    dist: trusty
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-6
          - gcc-6
    env: MYCXX=g++-6 MYCC=gcc-6
  - os: osx
    julia: 0.4
    env: MYCXX=${CXX} MYCC=${CC}

notifications:
  email: false
install:
  - export LCIOJLBUILDDIR=$(pwd)
  - if [ ! -e ${HOME}/lcio_bindir/CMakeLists.txt ]; then rm -rf ${HOME}/lcio_bindir; svn co svn://svn.freehep.org/lcio/tags/v02-07-01 ${HOME}/lcio_bindir; fi
  - cd ${HOME}/lcio_bindir; mkdir -p build; cd build
  - CXX=${MYCXX} CC=${MYCC} cmake ..
  - CXX=${MYCXX} CC=${MYCC} make && make install
  - cd ..
  - source ./setup.sh
  - cd ${LCIOJLBUILDDIR}

# uncomment the following lines to override the default test script
script:
  - export CXX=${MYCXX}
  - export CC=${MYCC}
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.update()'
  - julia -e 'Pkg.installed("CxxWrap") == nothing && Pkg.add("CxxWrap"); Pkg.checkout("CxxWrap"); Pkg.build("CxxWrap");'
  - julia -e 'Pkg.rm("LCIO"); Pkg.clone(pwd()); Pkg.build("LCIO"); Pkg.test("LCIO"; coverage=true)'
cache:
  directories:
  - ${HOME}/lcio_bindir
  - ${HOME}/.julia
