# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
sudo: required
dist: trusty
addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    packages:
    # install toolchains
    - gcc-6
    - g++-6
env: COMPILER=g++-6 CXX=g++-6 CC=gcc-6
julia:
  - nightly
notifications:
  email: false
install:
  - export LCIOJLBUILDDIR=$(pwd)
  - if [ ! -e ${HOME}/lcio_bindir/CMakeLists.txt ]; then rm -rf ${HOME}/lcio_bindir; svn co svn://svn.freehep.org/lcio/tags/v02-07-01 ${HOME}/lcio_bindir; fi
  - cd ${HOME}/lcio_bindir; mkdir -p build; cd build
  - cmake ..
  - make && make install
  - cd ..
  - source ./setup.sh
  - cd ${LCIOJLBUILDDIR}

# uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.update()'
  - julia -e 'Pkg.installed("CxxWrap") == nothing && Pkg.add("CxxWrap"); Pkg.checkout("CxxWrap"); Pkg.build("CxxWrap");'
  - julia -e 'Pkg.rm("LCIO"); Pkg.clone(pwd()); Pkg.build("LCIO"); Pkg.test("LCIO"; coverage=true)'
cache:
  directories:
  - ${HOME}/lcio_bindir
  - ${HOME}/.julia
